In [1]:
import pandas as pd
import numpy as np
import os

_root = os.getcwd().replace("scripts", "")
print(_root)
_data = os.path.join(_root, "datasets", "scraped")

/Users/michaelcullen/Documents/GitHub/StockAnalyserAndPredictor/

In [2]:
# df = pd.read_csv(os.path.join(_root, "datasets", "crypto", "BTCUSDT-trades-2021-11.csv"))
# df

In [3]:
df2 = pd.read_csv(os.path.join(_root, "datasets", "crypto", "BTCUSDT-1m-2021-11.csv"))
df2

,1635724800000,61299.81000000,61339.73000000,61284.28000000,61295.43000000,36.97964000,1635724859999,2267395.10970710,1171,24.16517000,1481711.90758030,0
0,1635724860000,61295.42,61333.58,61276.57,61296.60,16.79986,1635724919999,1.029857e+06,1013,7.86610,4.821988e+05,0
1,1635724920000,61296.61,61338.99,61204.82,61338.99,68.16703,1635724979999,4.176528e+06,1685,32.08120,1.965414e+06,0
2,1635724980000,61338.93,61399.93,61229.92,61245.11,29.34522,1635725039999,1.798862e+06,1398,16.95001,1.039049e+06,0
3,1635725040000,61245.12,61252.12,61115.33,61243.62,71.52817,1635725099999,4.376342e+06,1900,34.90847,2.135891e+06,0
4,1635725100000,61243.61,61319.28,61236.10,61310.94,25.59143,1635725159999,1.568422e+06,895,17.92210,1.098488e+06,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43194,1638316500000,57008.36,57012.79,56970.37,56980.48,15.84978,1638316559999,9.032576e+05,480,10.39480,5.923391e+05,0
43195,1638316560000,56980.48,57010.45,56980.00,57000.01,13.37989,1638316619999,7.626130e+05,524,5.32781,3.036695e+05,0
43196,1638316620000,57000.01,57011.92,56980.00,56992.95,15.47391,1638316679999,8.820380e+05,502,8.37167,4.771897e+05,0
43197,1638316680000,56992.94,57005.00,56980.00,56981.67,6.92027,1638316739999,3.943625e+05,438,4.36179,2.485589e+05,0
43198,1638316740000,56991.48,57012.20,56835.92,56950.56,33.14137,1638316799999,1.886946e+06,924,15.35747,8.741961e+05,0

In [4]:
df2.columns = ["time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", "ignore"]
df2["time"] = df2["time"] * 1000000
df2["close_time"] = df2["close_time"] * 1000000
df2

,time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
0,1635724860000000000,61295.42,61333.58,61276.57,61296.60,16.79986,1635724919999000000,1.029857e+06,1013,7.86610,4.821988e+05,0
1,1635724920000000000,61296.61,61338.99,61204.82,61338.99,68.16703,1635724979999000000,4.176528e+06,1685,32.08120,1.965414e+06,0
2,1635724980000000000,61338.93,61399.93,61229.92,61245.11,29.34522,1635725039999000000,1.798862e+06,1398,16.95001,1.039049e+06,0
3,1635725040000000000,61245.12,61252.12,61115.33,61243.62,71.52817,1635725099999000000,4.376342e+06,1900,34.90847,2.135891e+06,0
4,1635725100000000000,61243.61,61319.28,61236.10,61310.94,25.59143,1635725159999000000,1.568422e+06,895,17.92210,1.098488e+06,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43194,1638316500000000000,57008.36,57012.79,56970.37,56980.48,15.84978,1638316559999000000,9.032576e+05,480,10.39480,5.923391e+05,0
43195,1638316560000000000,56980.48,57010.45,56980.00,57000.01,13.37989,1638316619999000000,7.626130e+05,524,5.32781,3.036695e+05,0
43196,1638316620000000000,57000.01,57011.92,56980.00,56992.95,15.47391,1638316679999000000,8.820380e+05,502,8.37167,4.771897e+05,0
43197,1638316680000000000,56992.94,57005.00,56980.00,56981.67,6.92027,1638316739999000000,3.943625e+05,438,4.36179,2.485589e+05,0
43198,1638316740000000000,56991.48,57012.20,56835.92,56950.56,33.14137,1638316799999000000,1.886946e+06,924,15.35747,8.741961e+05,0

In [5]:
df3 = df2.copy()
df3 = df3[["time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume"]]
df3["time"] = pd.to_datetime(df3["time"], infer_datetime_format=True)
df3["close_time"] = pd.to_datetime(df3["close_time"], infer_datetime_format=True)

df3

,time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume
0,2021-11-01 00:01:00,61295.42,61333.58,61276.57,61296.60,16.79986,2021-11-01 00:01:59.999,1.029857e+06,1013,7.86610,4.821988e+05
1,2021-11-01 00:02:00,61296.61,61338.99,61204.82,61338.99,68.16703,2021-11-01 00:02:59.999,4.176528e+06,1685,32.08120,1.965414e+06
2,2021-11-01 00:03:00,61338.93,61399.93,61229.92,61245.11,29.34522,2021-11-01 00:03:59.999,1.798862e+06,1398,16.95001,1.039049e+06
3,2021-11-01 00:04:00,61245.12,61252.12,61115.33,61243.62,71.52817,2021-11-01 00:04:59.999,4.376342e+06,1900,34.90847,2.135891e+06
4,2021-11-01 00:05:00,61243.61,61319.28,61236.10,61310.94,25.59143,2021-11-01 00:05:59.999,1.568422e+06,895,17.92210,1.098488e+06
...,...,...,...,...,...,...,...,...,...,...,...
43194,2021-11-30 23:55:00,57008.36,57012.79,56970.37,56980.48,15.84978,2021-11-30 23:55:59.999,9.032576e+05,480,10.39480,5.923391e+05
43195,2021-11-30 23:56:00,56980.48,57010.45,56980.00,57000.01,13.37989,2021-11-30 23:56:59.999,7.626130e+05,524,5.32781,3.036695e+05
43196,2021-11-30 23:57:00,57000.01,57011.92,56980.00,56992.95,15.47391,2021-11-30 23:57:59.999,8.820380e+05,502,8.37167,4.771897e+05
43197,2021-11-30 23:58:00,56992.94,57005.00,56980.00,56981.67,6.92027,2021-11-30 23:58:59.999,3.943625e+05,438,4.36179,2.485589e+05
43198,2021-11-30 23:59:00,56991.48,57012.20,56835.92,56950.56,33.14137,2021-11-30 23:59:59.999,1.886946e+06,924,15.35747,8.741961e+05